# Generated by ChatGPT on 2026-01-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_roomblock_and_service_specialty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentChangeProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_start_time", models.DateTimeField()),
                ("original_end_time", models.DateTimeField()),
                ("proposed_start_time", models.DateTimeField()),
                ("proposed_end_time", models.DateTimeField()),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_message_id", models.CharField(blank=True, default="", max_length=120)),
                ("send_error", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_proposals",
                        to="core.appointment",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_proposals",
                        to="core.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_change_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_change_proposals",
                        to="core.room",
                    ),
                ),
                (
                    "proposed_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_change_proposals",
                        to="core.room",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["business", "status", "created_at"], name="core_appchang_busines_7c6b6d_idx"),
                    models.Index(fields=["business", "expires_at"], name="core_appchang_busines_52ac84_idx"),
                ]
            },
        ),
    ]
