# Generated by Django 5.2.10 on 2026-01-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_changeproposal_ops_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_weekdays', models.JSONField(blank=True, default=list)),
                ('time_window_start', models.TimeField(blank=True, null=True)),
                ('time_window_end', models.TimeField(blank=True, null=True)),
                ('min_notice_hours', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('send_error', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='appointmentchangeproposal',
            new_name='core_appoin_busines_32db01_idx',
            old_name='core_appchang_busines_7c6b6d_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentchangeproposal',
            new_name='core_appoin_busines_27a773_idx',
            old_name='core_appchang_busines_52ac84_idx',
        ),
        migrations.RenameIndex(
            model_name='roomblock',
            new_name='core_roombl_busines_020809_idx',
            old_name='core_roomblo_busines_6b4c56_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('scheduled', 'מתוכנן'), ('confirmed_by_client', 'אושר ע"י לקוח'), ('cancellation_requested', 'בקשת ביטול (ממתין לצוות)'), ('cancelled_by_client', 'בוטל ע"י לקוח'), ('cancelled_by_staff', 'בוטל ע"י צוות'), ('completed', 'הושלם'), ('no_show', 'לא הגיע')], default='scheduled', max_length=32),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.business'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.client'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='core.provider'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='core.service'),
        ),
        migrations.AddField(
            model_name='waitlistoffer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_offers', to='core.business'),
        ),
        migrations.AddField(
            model_name='waitlistoffer',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.waitlistentry'),
        ),
        migrations.AddField(
            model_name='waitlistoffer',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_offers', to='core.appointment'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['business', 'status', 'created_at'], name='core_waitli_busines_ec3981_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['business', 'provider', 'service'], name='core_waitli_busines_be5c35_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistoffer',
            index=models.Index(fields=['business', 'status', 'created_at'], name='core_waitli_busines_725d19_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistoffer',
            index=models.Index(fields=['business', 'expires_at'], name='core_waitli_busines_6ed181_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistoffer',
            index=models.Index(fields=['slot', 'status'], name='core_waitli_slot_id_355b99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlistoffer',
            unique_together={('entry', 'slot')},
        ),
    ]
