# Generated by ChatGPT for Stage 5 (Recall)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_waitlistentry_waitlistoffer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecallProtocol",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interval_days", models.PositiveIntegerField(default=90)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recall_protocols", to="core.business")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recall_protocols", to="core.service")),
            ],
            options={
                "unique_together": {("business", "service")},
            },
        ),
        migrations.CreateModel(
            name="RecallTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("due_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("offered", "Offered"), ("booked", "Booked"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("booked_appointment", models.ForeignKey(blank=True, help_text="If the client already booked (or accepted an offer), this points to the booked appointment.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recall_bookings", to="core.appointment")),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recall_targets", to="core.business")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recall_targets", to="core.client")),
                ("provider", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recall_targets", to="core.provider")),
                ("service", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recall_targets", to="core.service")),
                ("source_appointment", models.ForeignKey(help_text="The completed appointment that created this recall target.", on_delete=django.db.models.deletion.CASCADE, related_name="recall_targets", to="core.appointment")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["business", "status", "due_at"], name="core_recallt_business_8b45c8_idx"),
                    models.Index(fields=["business", "client", "service"], name="core_recallt_business_f28a47_idx"),
                ],
                "unique_together": {("business", "source_appointment")},
            },
        ),
        migrations.CreateModel(
            name="RecallOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined"), ("expired", "Expired"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_message_id", models.CharField(blank=True, default="", max_length=120)),
                ("send_error", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recall_offers", to="core.business")),
                ("slot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recall_offers", to="core.appointment")),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="core.recalltarget")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["business", "status", "created_at"], name="core_recallo_business_4a4b9c_idx"),
                    models.Index(fields=["business", "expires_at"], name="core_recallo_business_a5854f_idx"),
                    models.Index(fields=["slot", "status"], name="core_recallo_slot_ae4c19_idx"),
                ],
                "unique_together": {("target", "slot")},
            },
        ),
    ]
