# Generated by Django 5.2.10 on 2026-01-19 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recall_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('dry_run', 'Dry run'), ('sent', 'Sent'), ('failed', 'Failed')], default='dry_run', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='recalloffer',
            new_name='core_recall_busines_8f61b8_idx',
            old_name='core_recallo_business_4a4b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='recalloffer',
            new_name='core_recall_busines_b4eb98_idx',
            old_name='core_recallo_business_a5854f_idx',
        ),
        migrations.RenameIndex(
            model_name='recalloffer',
            new_name='core_recall_slot_id_b1a880_idx',
            old_name='core_recallo_slot_ae4c19_idx',
        ),
        migrations.RenameIndex(
            model_name='recalltarget',
            new_name='core_recall_busines_bc8be4_idx',
            old_name='core_recallt_business_8b45c8_idx',
        ),
        migrations.RenameIndex(
            model_name='recalltarget',
            new_name='core_recall_busines_58e407_idx',
            old_name='core_recallt_business_f28a47_idx',
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='receive_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='receive_weekly_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='weeklyreportlog',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_report_logs', to='core.business'),
        ),
        migrations.AddIndex(
            model_name='weeklyreportlog',
            index=models.Index(fields=['business', 'week_start', 'status', 'created_at'], name='core_weekly_busines_64bac8_idx'),
        ),
    ]
